# Generated by Django 4.0.5 on 2022-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('lastLogin', models.DateField()),
                ('numSearches', models.IntegerField()),
                ('likedRestaurants', models.ManyToManyField(to='restaurants.restaurant', verbose_name='list of liked restaurants')),
            ],
        ),
    ]
