# Generated by Django 4.0.5 on 2022-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='preference',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='numSearches',
            field=models.IntegerField(),
        ),
    ]
