# Generated by Django 4.0.5 on 2022-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_preference_name_restaurant_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='preference',
            name='cuisineKeyword',
        ),
        migrations.AddField(
            model_name='preference',
            name='tags',
            field=models.ManyToManyField(to='app.tag', verbose_name='keyword list'),
        ),
    ]
