# Generated by Django 4.0.5 on 2022-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_remove_preference_cuisinekeyword_preference_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likedRestaurants',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
