# Generated by Django 4.0.5 on 2022-07-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_user_id_preference_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='rating_threshold',
        ),
    ]
