# Generated by Django 4.0.5 on 2022-07-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_preference_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
    ]
