# Generated by Django 4.0.5 on 2022-06-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('rating_threshold', models.FloatField()),
                ('pricing_range', models.CharField(choices=[('$', 'Cheap'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], max_length=4)),
                ('location', models.CharField(max_length=40)),
                ('distance', models.IntegerField()),
                ('keywords', models.ManyToManyField(to='tags.tag', verbose_name='keyword list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='related user')),
            ],
        ),
    ]
