# Generated by Django 4.0.5 on 2022-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('latitude', models.FloatField(max_length=32)),
                ('longitude', models.FloatField(max_length=32)),
                ('rating', models.FloatField(default=None, max_length=32)),
                ('pricing', models.CharField(choices=[('$', 'Cheap'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], max_length=4)),
                ('categories', models.ManyToManyField(to='tags.tag', verbose_name='keyword list')),
            ],
        ),
    ]
